import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobile4U</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Mobile4U!</a>
        </h1>

        <p className={styles.description}>
          Something Big is coming{' '}
          <code className={styles.code}>Just wait and watch</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Mobile Prices &rarr;</h2>
            <p>We are going to inform you about current market rates of mobiles</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Mobile Comparison &rarr;</h2>
            <p>You can compare diffrent mobiles specs at time!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Upcoming Mobiles &rarr;</h2>
            <p>You can get prices and details of upcoming mobiles.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Latest News &rarr;</h2>
            <p>
              You can get latest news about mobiles.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Rohan Here !!
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}
