import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mobiles4U</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex" />
        <meta name="googlebot" content="noindex"></meta>

        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <div class={styles.Container}>
          <div class={styles.Container__Header}>
            <div class={styles.Container_Logo}>
              <h2>Mobile4u</h2>
            </div>
            <div class={styles.Container_SearchBar}>
              <h3>Search Bar</h3>
            </div>
          </div>
          <div class={styles.Container__Navbar}>
            <div class={styles.Container_Item}>News</div>
            <div class={styles.Container_Item}>Home</div>
            <div class={styles.Container_Item}>Rumours</div>
            <div class={styles.Container_Item}>Compare</div>
            <div class={styles.Container_Item}>Contact</div>
            <div class={styles.Container_Item}>Reviews</div>
          </div>


          <div className={styles.content}>
            <div className={styles.contentPage}>
              <div class={styles.ad}>Space for Banner</div>

              <div class={styles.componentHeadings}><h3>Latest News</h3>
                <h3>Views All</h3></div>
              <div class={styles.component1}>
                <div className={styles.componentContainer}>
                  <div class={styles.News}>News
                  </div>
                  <div class={styles.NewsAll}>
                    <div class={styles.news1}>Veiw All News
                    </div>
                    <div class={styles.news2}>Veiw All News
                    </div>
                  </div>
                </div>
                <div class={styles.TopBrands}>Top Brands
                </div>
              </div>

              <div class={styles.componentHeadings}><h3>Upcoming Mobiles</h3>
                <h3>Views All</h3></div>
              <div class={styles.component2}>
                <div className={styles.componentContainer}>
                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>


                </div>
                <div class={styles.TopBrands}>Top Brands
                </div>
              </div>

              <div class={styles.componentHeadings}><h3>Latest Mobiles</h3>
                <h3>Views All</h3></div>
              <div class={styles.component2}>
                <div className={styles.componentContainer}>
                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>


                </div>
                <div class={styles.TopBrands}>Top Brands
                </div>
              </div>

              <div class={styles.componentHeadings}><h3>Mobile Prices 60,000 Rs. to 80,000 Rs. </h3>
                <h3>Views All</h3></div>
              <div class={styles.component2}>
                <div className={styles.componentContainer}>
                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>


                </div>
                <div class={styles.TopBrands}>Top Brands
                </div>
              </div>


              <div class={styles.componentHeadings}><h3>Mobile Prices 80,000 Rs. to 100,000 Rs.</h3>
                <h3>Views All</h3></div>
              <div class={styles.component2}>
                <div className={styles.componentContainer}>
                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>


                </div>
                <div class={styles.TopBrands}>Top Brands
                </div>
              </div>


              <div class={styles.componentHeadings}><h3>Mobile Prices > 100,000 Rs.</h3>
                <h3>Views All</h3></div>
              <div class={styles.component2}>
                <div className={styles.componentContainer}>
                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>

                  <div class={styles.component}>
                    <div class={styles.subcomponent}></div>
                    <div>Name</div>
                  </div>


                </div>
                <div class={styles.TopBrands}>Top Brands
                </div>
              </div>


              <div class={styles.componentHeadings}><h3>Latest News</h3>
                <h3>Views All</h3></div>
              <div class={styles.component1}>
                <div className={styles.componentContainer}>
                  <div class={styles.News}>News
                  </div>
                  <div class={styles.NewsAll}>
                    <div class={styles.news1}>Veiw All News
                    </div>
                    <div class={styles.news2}>Veiw All News
                    </div>
                  </div>
                </div>
                {/* <div class={styles.TopBrands}>Top Brands
                </div> */}
              </div>






            </div>
          </div>
        </div>

        <div class={styles.footer}>
          <div class={styles.domainname}>Mobile4u</div>
          <div class={styles.links}>
            <div class={styles.colLinks}>
              <div>info</div>
              <div>get in touch</div>
              <div>social</div>
              <div>what we offer</div>
            </div>
            <div class={styles.colLinks}>
              <div>about us</div>
              <div>contact us</div>
              <div>facebook</div>
              <div>mobile phones</div>
            </div>

            <div class={styles.colLinks}>
              <div>FAQs</div>
              <div>advertise</div>
              <div>twitter</div>
              <div>news</div>
            </div>

            <div class={styles.colLinks}>
              <div>blogs</div>
              <div>careers</div>
              <div>linkedIn</div>
              <div>Reviews</div>
            </div>

          </div>

          <div class={styles.copyright}>
            <div class={styles.copyright1}>copyright c 2022 , Mobile4u.com</div>
            <div class={styles.terms}>
              <div>terms </div>
              <div>policy </div>
              <div>sitemap </div>
            </div>
          </div>
        </div>

      </main>


    </div>
  )
}
